apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  selector:
    app: sample-app
    tier: app
  type: LoadBalancer
  ports:
    ## While running on production cluster, please use 'port: 80'
  - port: 8080
    targetPort: 8080
